// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // マイグレーションはDirect Connection（DIRECT_URL）を優先
    // Supabaseの場合、Transaction Pooler（port 6543）はマイグレーション非対応
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
